"""Add hotel model

Revision ID: 8baa260283c7
Revises: fe340e6ab2e8
Create Date: 2024-07-04 16:06:19.673885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8baa260283c7'
down_revision = 'fe340e6ab2e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('price_per_night', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotel')
    # ### end Alembic commands ###
