"""Initial migration

Revision ID: fe340e6ab2e8
Revises: 
Create Date: 2024-06-19 14:50:51.281738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe340e6ab2e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
